#!/usr/bin/env python3
"""Generate framework bindings from Infiloop specs."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from repo_tools.common import (
    GENERATED_DYNAMODB_PATH,
    GENERATED_WEB_AGENTS_PATH,
    GENERATED_WEB_MOCKS_PATH,
    iter_agent_dirs,
    iter_table_paths,
    load_json,
)


def constant_name(table_name: str) -> str:
    return f"{table_name.upper()}_TABLE"


def pascal_name(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_") if part)


def load_tables() -> list[dict[str, Any]]:
    return [load_json(path) for path in iter_table_paths()]


def load_agents() -> list[dict[str, Any]]:
    return [load_json(agent_dir / "spec.json") for agent_dir in iter_agent_dirs()]


def render_python_value(value: Any, indent: int = 0) -> str:
    prefix = "    " * indent
    child_prefix = "    " * (indent + 1)
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = ["{"]
        for key in sorted(value):
            lines.append(f"{child_prefix}{json.dumps(key)}: {render_python_value(value[key], indent + 1)},")
        lines.append(f"{prefix}}}")
        return "\n".join(lines)
    if isinstance(value, list):
        if not value:
            return "[]"
        lines = ["["]
        for item in value:
            lines.append(f"{child_prefix}{render_python_value(item, indent + 1)},")
        lines.append(f"{prefix}]")
        return "\n".join(lines)
    return repr(value)


def render_dynamodb_py(tables: list[dict[str, Any]]) -> str:
    lines = [
        '"""Generated DynamoDB helpers. Run `npm run codegen` to refresh."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
    ]

    for table in sorted(tables, key=lambda item: item["table_name"]):
        table_value = {
            "table_name": table["table_name"],
            "owner_agent": table["owner_agent"],
            "partition_key": table["primary_key"]["partition_key"],
            "sort_key": table["primary_key"].get("sort_key"),
            "attributes": table["attributes"],
        }
        lines.append(f"{constant_name(table['table_name'])}: dict[str, Any] = {render_python_value(table_value)}")
        lines.append("")

    lines.append("TABLES: dict[str, dict[str, Any]] = {")
    for table in sorted(tables, key=lambda item: item["table_name"]):
        lines.append(f"    {json.dumps(table['table_name'])}: {constant_name(table['table_name'])},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_mock_agents_ts(agents: list[dict[str, Any]]) -> str:
    external_agents = [agent for agent in agents if agent["connectivity"] == "external"]
    lines = [
        "// Generated by repo_tools/codegen.py. Do not edit by hand.",
        "",
        "export type AgentResponse = {",
        "  message: string;",
        "  agent: string;",
        "  mocked: boolean;",
        "};",
        "",
    ]
    for agent in sorted(external_agents, key=lambda item: item["name"]):
        function_name = f"mockCall{pascal_name(agent['name'])}"
        lines.extend(
            [
                f"export async function {function_name}(): Promise<AgentResponse> {{",
                "  return {",
                '    message: "lambda was called",',
                f'    agent: "{agent["name"]}",',
                "    mocked: true,",
                "  };",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def render_agents_ts(agents: list[dict[str, Any]]) -> str:
    external_agents = [agent for agent in agents if agent["connectivity"] == "external"]
    mock_imports = [
        f"mockCall{pascal_name(agent['name'])}"
        for agent in sorted(external_agents, key=lambda item: item["name"])
    ]
    import_clause = ", ".join([*mock_imports, "type AgentResponse"])
    lines = [
        "// Generated by repo_tools/codegen.py. Do not edit by hand.",
        "",
        f'import {{ {import_clause} }} from "./mockAgents";',
        "",
        "async function callLambdaUrl(url: string): Promise<AgentResponse> {",
        "  const response = await fetch(url, {",
        '    method: "POST",',
        '    headers: { "content-type": "application/json" },',
        '    body: JSON.stringify({ source: "webUI" }),',
        "    cache: \"no-store\",",
        "  });",
        "",
        "  if (!response.ok) {",
        "    throw new Error(`Lambda call failed with status ${response.status}`);",
        "  }",
        "",
        "  return (await response.json()) as AgentResponse;",
        "}",
        "",
    ]

    for agent in sorted(external_agents, key=lambda item: item["name"]):
        pascal = pascal_name(agent["name"])
        env_name = f"{agent['name'].upper()}_URL"
        mock_fn = f"mockCall{pascal}"
        call_fn = f"call{pascal}"
        lines.extend(
            [
                f"export async function {call_fn}(): Promise<AgentResponse> {{",
                f"  const url = process.env.{env_name};",
                "  if (!url) {",
                f"    return {mock_fn}();",
                "  }",
                "  return callLambdaUrl(url);",
                "}",
                "",
            ]
        )

    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        existing = path.read_text() if path.exists() else ""
        if existing != content:
            print(f"Generated file is stale: {path}")
            return False
        return True

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"Wrote {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    tables = load_tables()
    agents = load_agents()
    outputs = {
        GENERATED_DYNAMODB_PATH: render_dynamodb_py(tables),
        GENERATED_WEB_MOCKS_PATH: render_mock_agents_ts(agents),
        GENERATED_WEB_AGENTS_PATH: render_agents_ts(agents),
    }

    ok = True
    for path, content in outputs.items():
        ok = write_or_check(path, content, args.check) and ok

    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
